// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv1MQ4CQWMn0tz7pEvUyrPbkQ-W5L0GYU',
    appId: '1:699991162085:web:b315d105e5c7a11d78e80c',
    messagingSenderId: '699991162085',
    projectId: 'my-chat-project-new',
    authDomain: 'my-chat-project-new.firebaseapp.com',
    storageBucket: 'my-chat-project-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqfFYWL7DIQH4SRe62vSUrDO2zNA4fycI',
    appId: '1:699991162085:android:5866e512c443e64078e80c',
    messagingSenderId: '699991162085',
    projectId: 'my-chat-project-new',
    storageBucket: 'my-chat-project-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Nlk-NLvUwREfuFKnxhpwY5hXRM1xoLw',
    appId: '1:699991162085:ios:d201ec5defb5d35178e80c',
    messagingSenderId: '699991162085',
    projectId: 'my-chat-project-new',
    storageBucket: 'my-chat-project-new.appspot.com',
    iosBundleId: 'Com.nanak.chatModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Nlk-NLvUwREfuFKnxhpwY5hXRM1xoLw',
    appId: '1:699991162085:ios:d201ec5defb5d35178e80c',
    messagingSenderId: '699991162085',
    projectId: 'my-chat-project-new',
    storageBucket: 'my-chat-project-new.appspot.com',
    iosBundleId: 'Com.nanak.chatModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv1MQ4CQWMn0tz7pEvUyrPbkQ-W5L0GYU',
    appId: '1:699991162085:web:c98f6587cea6229078e80c',
    messagingSenderId: '699991162085',
    projectId: 'my-chat-project-new',
    authDomain: 'my-chat-project-new.firebaseapp.com',
    storageBucket: 'my-chat-project-new.appspot.com',
  );
}
